### ISSUE TITLE
Filter selection/download and plotting do not function

### ISSUE THREAD

**Issue by exowanderer** [hover2pi/svo_filters#2]
No plots open up while I am going through the ldc_demo.ipynb in ExoCTK package (using it's svo_filter functions)

```
https://github.com/ExoCTK/ExoCTK/blob/master/ExoCTK/notebooks/ldc_demo.ipynb
```

Specifically, if I call:

```
H_band = core.Filter('2MASS.H')
```

says 

```
Current filters: 2MASS.J, 2MASS.Ks, IRAC.I1, IRAC.I2, IRAC.I3, IRAC.I4, Kepler.K, WFC3_IR.G102, WFC3_IR.G141, WFC3_UVIS2.F814W, WFC3_UVIS2.F850LP, WISE.W1, WISE.W2, WISE.W3, WISE.W4 

No filters match /Users/jfraine/anaconda3/lib/python3.6/site-packages/ExoCTK-0.0.dev616-py3.6-macosx-10.7-x86_64.egg/ExoCTK/data/filters/2MASS.H
Would you like me to download it? [y/n] y
```

I select 'y' for yes

and svo_filter replies:

```
A full list of available filters from the
SVO Filter Profile Service can be found at
http://svo2.cab.inta-csic.es/theory/fps3/

Enter the band name to retrieve (e.g. 2MASS/2MASS.J): 2MASS/2MASS.H
Band stored as 2MASS.H
No filter named 2MASS/2MASS.H
```

No matter how many times I use the `H_band = core.Filter('2MASS.H')` command, it asks me to download the filter, then says that there is "No Filter named 2MASS/2MASS.H". 

Moreover, in the svo_filters comment "Current filters" include `2MASS.Ks`. So I tried to switch to `2MASS.Ks` instead of `2MASS.H` and received the exact same issue `No filter named 2MASS/2MASS.Ks`.

I think that the data is being downloaded into one directory and accessed from another.

**Comment by hover2pi** [comment]
If you do `python setup.py develop` instead of `python setup.py install' it works fine! I have to figure out why.

**Comment by hover2pi** [comment]
Closing for now.
