### ISSUE TITLE
release 0.4.0 and astroquery import error

### ISSUE THREAD

**Issue by falkben** [hover2pi/svo_filters#32]
Having a problem with release 0.4.0, which we are using as a dependency in exoctk.

In https://github.com/hover2pi/svo_filters/blob/master/svo_filters/svo.py#L17

```python
    from astroquery.svo_fps import SvoFps
```

Getting:

```
ModuleNotFoundError: No module named 'astroquery.svo_fps'
```

astroquery version: `0.4.1`

Currently pinning svo_filters to `0.3.0` fixes the problem.

**Comment by hover2pi** [comment]
Oh yeah. This is because ‘svo_filters’ requires ‘astroquery’ 0.4.2 or greater. There is no release on conda or PyPI for >0.4.1 so the dependency has to be set to the ‘astroquery’ master branch on Github.

But ‘exoctk’ can use ‘svo_filters’ v0.3.0 with no problem.

**Comment by hover2pi** [comment]
@falkben `svo_filters` v0.4.0+ requires `astroquery` v0.4.2+ but `pip install astroquery==0.4.2.dev6449` throws the error

```
ERROR: Requested astroquery==0.4.2.dev6449 from https://files.pythonhosted.org/packages/65/41/3cc633331a276f78aa5fa110c7dc71e146dd7d14346f3460534a264e0a5d/astroquery-0.4.2.dev6449.tar.gz#sha256=df7786a5ba87c966f705f6fce02d73bd7c48a748d7e0a89f0531bcd544a7a074 has different version in metadata: '0.4.2.dev0'
```

Even though the release is here: https://pypi.org/project/astroquery/#history

Any ideas how to get this to install with the `svo_filters` environment so `exoctk` v1.2 can use it without any problems?

**Comment by falkben** [comment]
noticed a new release 0.3.1 for exo-ctk, compared to 0.3.0 looks like the only difference is this WFC3_IR.G102 file?
