### ISSUE TITLE
Repeated wavelength axis or floating point precision issue with ZTF filters, maybe others.

### ISSUE THREAD

**Issue by emirkmo** [hover2pi/svo_filters#35]
Easiest way to reproduce is to do:
```
bp = svo.Filter('Palomar/ZTF.g')
bp.wave[0][-4:]
```
returns `[0.56459999, 0.56470001, 0.56480002, 0.56480002]𝜇m`

Where we can see the last 2 elements are repeated. This is true regardless if binning is used or not, for example 

```
svo.Filter('Palomar/ZTF.g',n_bins=50).wave.flatten()[-4:]
```
return `[0.5517, 0.55180001, 0.55190003, 0.55190003]𝜇m`; the same repeated element. Just to be clear, it's not only the final element that is repeated, but the one that is most readily noticeable. This is a problem as many spectral analysis software expect a monotonically increasing spectroscopic axis and fail. E.g. https://github.com/spacetelescope/synphot_refactor or Astropy specutils package. 

Any suggestions or ways to avoid it?

**Comment by hover2pi** [comment]
Thanks for the Issue, @emirkmo ! Yeah I haven't seen this until now. I can include a check for monotonicity and just add a tiny offset if any wavelengths repeat. If you have other ideas, let me know!

**Comment by emirkmo** [comment]
@hover2pi Okay I made a PR #38 that has my proposed fix for the issue.
