### ISSUE TITLE
Return more informative error for web query if cause of error isn't naming the wrong filter

### ISSUE THREAD

**Issue by emirkmo** [hover2pi/svo_filters#37]
Description:

If there are connection errors (such as from repeated queries, network issues, etc.), the returned error still assumes the cause of the exception to be using the wrong SVO filter name. Also, with a naked try exception catch, it catches SysExit as well.

Expected behavior:

`load_web` should raise ConnectionError, or other errors, not only IndexError.

Proposed Solution:

Modify `load_web` to catch only IndexError, and otherwise raise the exception.

**Comment by hover2pi** [comment]
Resolved in #39

**Comment by hover2pi** [comment]
Your improvements are implemented in v0.4.3, available [on PyPI](https://pypi.org/project/svo-filters/0.4.3/) now. Thanks for the fix!

**Comment by emirkmo** [comment]
Thanks for going through the PRs! This will be helpful!
